language: go
go:
- 1.10.x
script:
- make setup
- make build
- make db.setup
- make test
deploy:
  provider: heroku
  buildpack: https://github.com/kr/heroku-buildpack-go.git
  api_key:
    secure: "HmUDsYLx83RzvqRx5V4rvXRnf9if4V9wYnhB3LbmSdFBoTuQ8riWwzd/j3MKDNdRz2Ct1cmadogG9PZFMnbFLqKjSasQvb9s/dla/3FHjo+IGJKEovlfbvAEmCQIZbgl+uCoxocHOjtjsJzVN984PQT9b7zsuB3aLvyBE2ZZau0OBNmXMQ56SJpiZh0Alquff6zk5OWw3yV4l+sFaZWQFoWf6mb3qUbdJ8uuBLKduLzc6RknqhWVGIij+Bwl/FVhDQZjcvdJ7YyVvpiUUXwLxuYeRL2balIXbhicDQ7tx4bKwlA2yXOZ+VRIKMM950AI2AI/4nBf7e+OFk77SiBfkd2J4Lj/jjZyZGCDAWdoJYS9R8vOdKKCK8CbYvWg/vdi5m09YQFed1YglVXjRYu4RVlVpcQDdtI/7vN6Ug5nKPPF/VBULDa2whjI2cOwVmn4BcM8dLE6dPWFGV5JRdxKXndmhHCtri5GEdI7SdFUimMqChYMmLdmIDNkPYMzZ6NGcM3x767YzZ1WFWptLmtIUv2HSAtB3nKG+ADmwT6S1To+d0hp9RsKdlGHtFp5zIvyP+rDr/+Zc/D7MN+uCBZPGMlMlNUXeeg3tE1Tyn1RgyQNXu+bjM0gH9fS3ZYBxpmvxE1UVkPwCihWSl/rfpvIN7VFvx37UsX0cQBjgWO7xh0="
  app: go-todo-list
  on:
    repo: amitansh-gangwar/go-todo-list
